# Generated by Django 4.2.6 on 2023-10-28 03:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coupons",
            new_name="Coupon",
        ),
    ]
