# Generated by Django 4.2.6 on 2023-10-28 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0002_rename_coupons_coupon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="acitve",
            new_name="active",
        ),
    ]
